php_fpm_daemon: php-fpm
php_fpm_conf_path: "/etc/fpm"
php_fpm_pool_conf_path: "/etc/php-fpm.d/www.conf"
php_fpm_pool_user: apache
php_fpm_pool_group: apache

php_enable_php_fpm: true
php_fpm_listen: "/var/run/php-fpm.sock"
php_fpm_listen_allowed_clients: "127.0.0.1"
php_fpm_listen_owner: "nginx"
php_fpm_listen_group: "nginx"
php_fpm_listen_mode: "0660"
php_fpm_pm_max_children: 50
php_fpm_pm_start_servers: 5
php_fpm_pm_min_spare_servers: 5
php_fpm_pm_max_spare_servers: 5

php_composer_path: /usr/local/bin
php_composer_install: "{{ php_composer_path }}/composer"
# CUSTOMIZE HERE
php_composer_auto_update: false
# CUSTOMIZE HERE
# php54, php56, php70, php71, php72
php_version: php72
# CUSTOMIZE HERE
php_packages:
  - php
  - php-cli
  - php-common
  - php-devel
  - php-fpm
  - php-gd
  - php-imap
  - php-ldap
  - php-mbstring
  - php-opcache
  - php-pdo
  - php-pear
  - php-pecl-apcu
  - php-pecl-redis
  - php-xml
  - php-xmlrpc
  - php-mysqlnd
  - zip
  - unzip
  - php-zip
