# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"
  # CUSTOMIZE HERE
  config.vm.network :forwarded_port, guest: 80, host: 8082
  # CUSTOMIZE HERE
  config.vm.network "private_network", ip: "192.168.77.102"
  # CUSTOMIZE HERE
  config.vm.provider :virtualbox do |v|
    v.name = "laravel-blog-example"
    v.memory = 512
    v.cpus = 1
  end
  # CUSTOMIZE HERE
  config.vm.hostname = "lavarel-blog-example"

  config.vm.synced_folder './', '/vagrant', type: "rsync",
  rsync__exclude: [".git/", ".idea/", ".vagrant/", "storage/framework/sessions"],
  rsync__chown: false

  # Configure the window for gatling to coalesce writes.
  if Vagrant.has_plugin?("vagrant-gatling-rsync")
    config.gatling.latency = 2.5
    config.gatling.time_format = "%H:%M:%S"
  end

  # Automatically sync when machines with rsync folders come up.
  config.gatling.rsync_on_startup = false
  # vagrant gatling-rsync-auto manually

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.host_key_checking = false
    ansible.become = true
    ansible.become_user = "root"
  end
end
